### ISSUE TITLE
只要引入 agora-electron-sdk 就报错  node is not a valid Win32 application.

### ISSUE THREAD

**Issue by qisihan** [AgoraIO-Community/Agora-Electron-Quickstart#23] opened 2020-04-14 09:07 UTC
Uncaught Error: \\?\G:\Agora-Electron-Quickstart\Agora-Electron-React\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.
\\?\G:\Agora-Electron-Quickstart\Agora-Electron-React\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\build\Release\agora_node_ext.node
    at process.func [as dlopen] (electron/js2c/asar.js:155)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881)
    at Object.func [as .node] (electron/js2c/asar.js:155)
    at Module.load (internal/modules/cjs/loader.js:701)
    at tryModuleLoad (internal/modules/cjs/loader.js:633)
    at Function.Module._load (internal/modules/cjs/loader.js:625)
    at Module.require (internal/modules/cjs/loader.js:739)
    at require (internal/modules/cjs/helpers.js:14)
    at Object.<anonymous> (G:\Agora-Electron-Quickstart\Agora-Electron-React\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\js\Api\index.js:6)
    at Object.<anonymous> (G:\Agora-Electron-Quickstart\Agora-Electron-React\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\js\Api\index.js:3786)

**Comment by plutoless** [comment] 2020-04-19 07:29
duplicate of https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/issues/22

**Closed by plutoless** 2020-04-19 07:29 UTC
